### ISSUE TITLE
Typo in HDInsight lab

### ISSUE THREAD

**Issue by vanitech** [MSRConnections/Azure-training-course#178]
Hdinsight on Linux lab:

Step 6 (windows):

"C:\Program Files (x86)\PuTTY\pscp" *.py username@clustername-ssh.azurehdinsight.net:

Should read without the quote:
"C:\Program Files (x86)\PuTTY\pscp *.py username@clustername-ssh.azurehdinsight.net:

(as reported by Mark Garcia)

**Comment by jeffprosise** [comment]
That second quote is required. The command won't work without it.
