### ISSUE TITLE
Azure Image Processing HOL: talks about auto pricing instead of cell classification

### ISSUE THREAD

**Issue by kalpitad** [MSRConnections/Azure-training-course#184]
There is a bunch of stuff about predicting automobile prices that should probably be updated to stuff about cell classification.
- Classification is used to make a prediction from a defined set of values, such as the make of a car (for example, Honda or BMW). Regression is used to make a prediction from a continuous set of values, such as a person's age or the price of an automobile.
- The goal of this lab is to predict the price of an automobile from a set of input features, so you will use a regression model.

**Comment by vanitech** [comment]
resolved
