### ISSUE TITLE
Azure Image Processing HOL: Suggestions

### ISSUE THREAD

**Issue by kalpitad** [MSRConnections/Azure-training-course#185]
- After the “Import Images” step, it says “To see what this dataset looks like, click the output port (the circle in it) at the bottom of the module and select Visualize.”, but because we haven’t clicked “Run” yet, we can’t see anything. That would be a good time to introduce folks to the "Run" button.
- To save time during runs (and demonstrate how intermediate data sets can be saved and used later), it would be useful to add some steps to save the joined data as a separate data set and then drag it back onto the canvas as an input into “Split Data”. Based on the workshop today, that seems to save more than 5 min on future runs.
- It wasn’t clear to me which side of “Split Data” was the 80% and which was the 20%. Exercise 5 seems to be about using 80% of the data (the left side) to train the model, and Exercise 6 is all about using the remainder 20% (the left side) to score the model. Maybe giving that overview would be helpful for folks who are new to ML.
- I didn’t realize that the “Train Model” module takes: 1) a data set, and 2) an algorithm. Maybe that would also be helpful to explain for folks who are new to ML.

**Comment by vanitech** [comment]
resolved!
