### ISSUE TITLE
HDInsight cluster creation Advanced settings 

### ISSUE THREAD

**Issue by vanitech** [MSRConnections/Azure-training-course#189]
Advances settings step as part of the HDInsight automated cluster creation is missing in the screenshot. One student was confused about the discrepancy..

**Comment by jeffprosise** [comment]
Will review this and fix. Thanks!

**Comment by jeffprosise** [comment]
Just went through the Spark lab and the workflow is exactly as described in the lab. Not sure where "Advanced Settings" comes in. Do you have more detail?

**Comment by jeffprosise** [comment]
I'll bet this had to do with having to click "Create new" to create a new storage account in the "Storage" blade in Exercise 1. I added instructions to the lab and will consider this closed unless the issue applied to something else.
